function [dotX,A,B] = carLinear(in1,in2,in3)
%CARLINEAR Linear state-space equation of car dynamics. Linearize around (0,0)
%    [DOTX,A,B] = CARLINEAR(X,U,params)
%   Inputs:
%       X         : State vector = [vx vy d_psi]'
%                   vx : Car longitudinal velocity [m/s]
%                   vy : Car lateral velocity [m/s]
%                   d_psi : Yaw-rate [rad/s]
%       U         : Input vector = [delta Fxw2]'
%                   delta : Steering-angle [rad]
%                   Fxw2 : Longitudinal Force applied on car [N]
%       params    : Parameters = [Cy1 Cy2 l1 l2 m J]'
%                   Cy1 : Cornering stiffness of front wheel.
%                   Cy2 : Cornering stiffness of rear wheel.
%                   l1 : Distance between front axle and centre of gravity. Unit: [m]
%                   l2 : Distance between rear axle and centre of gravity. Unit: [m]
%                   m : Vehicle mass. Unit: [Kg]
%                   J : Inertia around z-axis of vehicle Unit. Unit: [Kg.m^2]
%   Outputs:
%       dotX    : Symbolic expression of dotX = dX/dt = [d_vx d_vy dd_psi]
%       A       : Matrix from linear expression dX/dt = A*X + B*U
%       B       : Matrix from linear expression dX/dt = A*X + B*U
%   Author : Julius D.
%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Feb-2021 13:29:43

Cy1 = in3(1,:);
Cy2 = in3(2,:);
Fxw2 = in2(2,:);
J = in3(6,:);
d_psi = in1(3,:);
delta = in2(1,:);
l1 = in3(3,:);
l2 = in3(4,:);
m = in3(5,:);
vx = in1(1,:);
vy = in1(2,:);
t2 = Cy1.*l1;
t3 = Cy2.*l2;
t4 = l1.^2;
t5 = l2.^2;
t6 = vx.^2;
t7 = Cy1+Cy2;
t8 = 1.0./J;
t9 = 1.0./m;
t10 = 1.0./vx;
t11 = -t3;
t12 = m.*t6;
t13 = t2+t11+t12;
dotX = [Fxw2.*t9;Cy1.*delta.*t9-d_psi.*t9.*t10.*t13-t7.*t9.*t10.*vy;-t8.*t10.*(t2.*vy+t11.*vy+d_psi.*l1.*t2+d_psi.*l2.*t3-delta.*t2.*vx)];
if nargout > 1
    A = reshape([0.0,0.0,0.0,0.0,-t7.*t9.*t10,-t8.*t10.*(t2+t11),0.0,-t9.*t10.*t13,-t8.*t10.*(l1.*t2+l2.*t3)],[3,3]);
end
if nargout > 2
    B = reshape([0.0,Cy1.*t9,t2.*t8,t9,0.0,0.0],[3,2]);
end
