function dotX = carNonlinearVxConstant(in1,delta,vx,in4)
%CARNONLINEARVXCONSTANT Nonlinear state-space equation with constant longitudinal velocity of car dynamics
%    DOTX = CARNONLINEARVXCONSTANT(X,U,vx,params)
%   Inputs:
%       X       : State vector = [vy d_psi]'
%                   vy      : Car lateral velocity [m/s]
%                   d_psi   : Yaw-rate [rad/s]
%       U       : Input vector = [delta]'
%                   delta   : Steering-angle [rad]
%       vx      : Car longitudinal velocity [m/s]
%       params  : Parameters = [Cy1 Cy2 l1 l2 m J]'
%                   Cy1     : Cornering stiffness of front wheel.
%                   Cy2     : Cornering stiffness of rear wheel.
%                   l1      : Distance between front axle and centre of gravity. Unit: [m]
%                   l2      : Distance between rear axle and centre of gravity. Unit: [m]
%                   m       : Vehicle mass. Unit: [Kg]
%                   J       : Inertia around z-axis of vehicle Unit. Unit: [Kg.m^2]
%   Outputs:
%       dotX    : Symbolic expression of dotX = dX/dt = [d_vy dd_psi]               
%   Author : Julius D.
%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Feb-2021 13:29:43

Cy1 = in4(1,:);
Cy2 = in4(2,:);
J = in4(6,:);
d_psi = in1(2,:);
l1 = in4(3,:);
l2 = in4(4,:);
m = in4(5,:);
vy = in1(1,:);
t2 = cos(delta);
t3 = sin(delta);
t4 = d_psi.^2;
t5 = delta.*2.0;
t6 = l2.^2;
t7 = vx.^2;
t8 = vy.^2;
t13 = 1.0./vx;
t9 = t2.^2;
t10 = sin(t5);
t11 = t2.*vx;
t12 = t3.*vy;
t14 = d_psi.*l1.*t3;
t15 = t11+t12+t14;
t16 = 1.0./t15;
dotX = [-(t13.*t16.*(Cy2.*t3.*t8-(Cy1.*t7.*t10)./2.0+Cy2.*t11.*vy+Cy1.*t9.*vx.*vy+d_psi.*m.*t7.*t12+d_psi.*m.*t11.*1.0./t13.^2+Cy2.*d_psi.*l1.*t12-Cy2.*d_psi.*l2.*t11-Cy2.*d_psi.*l2.*t12+Cy1.*d_psi.*l1.*t9.*vx-Cy2.*l1.*l2.*t3.*t4+l1.*m.*t3.*t4.*t7))./m;-(t13.*t16.*(Cy2.*d_psi.*t6.*t11+Cy2.*d_psi.*t6.*t12-Cy2.*l2.*t3.*t8-(Cy1.*l1.*t7.*t10)./2.0-Cy2.*l2.*t11.*vy-Cy2.*d_psi.*l1.*l2.*t12+Cy2.*l1.*t3.*t4.*t6+Cy1.*l1.*t9.*vx.*vy+Cy1.*d_psi.*l1.^2.*t9.*vx))./J];
